In [1]:
import pandas as pd

### Sacramento pandas
1. Load the csv
2. run some transformations
    - Capitalize 'city'
    - convert to int:
        - 'zip'
        - 'beds'
        - 'baths'
        - 'sq__ft'
        - 'price'
    - convert to float:
        - 'latitude'
        - 'longitude'
    - rename 'sq__ft' to'sq_ft'
    - convert 'sale_Date' into format: "YYYY-MM-DD"

In [2]:
df = pd.read_csv("Sacramentorealestatetransactions.csv")

In [3]:
df.head(5)

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

In [4]:
type(df['street'])

pandas.core.series.Series

I'm a Series!

In [5]:
df['street'].head(5)

0        3526 HIGH ST
1         51 OMAHA CT
2      2796 BRANCH ST
3    2805 JANETTE WAY
4     6001 MCMAHON DR
Name: street, dtype: object

In [6]:
type(df[['street']])

pandas.core.frame.DataFrame

In [7]:
df[['street']].head(5)

street
0      3526 HIGH ST
1       51 OMAHA CT
2    2796 BRANCH ST
3  2805 JANETTE WAY
4   6001 MCMAHON DR

In [8]:
# Let me create a copy that I can mess up
df_clean = df.copy()

### 1: Replace "" in 'sqft' with "_"

In [9]:
df_clean.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [10]:
list(df_clean.columns)

['street',
 'city',
 'zip',
 'state',
 'beds',
 'baths',
 'sq__ft',
 'type',
 'sale_date',
 'price',
 'latitude',
 'longitude']

In [11]:
type(df_clean.columns)

pandas.core.indexes.base.Index

In [12]:
for i in df_clean.columns:
    print(i)

street
city
zip
state
beds
baths
sq__ft
type
sale_date
price
latitude
longitude


In [13]:
df_clean.columns = [col.replace("__", "_") for col in list(df_clean.columns)]

In [14]:
df_clean.head(5)

street        city    zip state  beds  baths  sq_ft         type  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1    836  Residential   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1   1167  Residential   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1    796  Residential   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1    852  Residential   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1    797  Residential   

                      sale_date  price   latitude   longitude  
0  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

### 2. Capitalize the 'city' column

In [15]:
df_clean['city'] = df['city'].str.capitalize()

In [16]:
df_clean.head()

street        city    zip state  beds  baths  sq_ft         type  \
0      3526 HIGH ST  Sacramento  95838    CA     2      1    836  Residential   
1       51 OMAHA CT  Sacramento  95823    CA     3      1   1167  Residential   
2    2796 BRANCH ST  Sacramento  95815    CA     2      1    796  Residential   
3  2805 JANETTE WAY  Sacramento  95815    CA     2      1    852  Residential   
4   6001 MCMAHON DR  Sacramento  95824    CA     2      1    797  Residential   

                      sale_date  price   latitude   longitude  
0  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

### 3. Converts column types

In [17]:
df_clean.dtypes

street        object
city          object
zip            int64
state         object
beds           int64
baths          int64
sq_ft          int64
type          object
sale_date     object
price          int64
latitude     float64
longitude    float64
dtype: object

##### Pandas already inferred the right types when using pd.read_csv().
##### How would I change it if I wanted to?

In [18]:
df_clean['latitude'].astype(int)

0      38
1      38
2      38
3      38
4      38
       ..
980    38
981    38
982    38
983    38
984    38
Name: latitude, Length: 985, dtype: int64

### 4. Convert weird date string into 'YYYY-MM-DD' representation

In [19]:
df_clean["sale_date"] = pd.to_datetime(df_clean["sale_date"], infer_datetime_format = True)

/opt/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)


In [20]:
df_clean.to_pickle("clean_sacramento.pkl")
df_clean.to_csv("clean_sacramento.csv")

### General pandas stuff, plus a little bit a numpy

In [21]:
import numpy as np

In [22]:
np.random.random_sample((5,))

array([0.4926793 , 0.60295453, 0.06090239, 0.09067633, 0.22619248])

In [23]:
np.random.random_sample((3, 2))

array([[0.02275141, 0.58124336],
       [0.27400607, 0.06381637],
       [0.92348553, 0.42647195]])

In [24]:
col_names = ["banana_density", "banana_mass", "apple_density", "apple_mass"]
df = pd.DataFrame(np.random.random_sample((10, 4)), columns = col_names)

In [25]:
df

banana_density  banana_mass  apple_density  apple_mass
0        0.560474     0.799471       0.553962    0.049969
1        0.727410     0.772222       0.721854    0.492099
2        0.940427     0.714961       0.644480    0.536481
3        0.302396     0.952872       0.003977    0.930725
4        0.241399     0.247323       0.272998    0.873663
5        0.329119     0.221963       0.725415    0.764441
6        0.973106     0.434359       0.370370    0.325287
7        0.948926     0.717877       0.903151    0.238228
8        0.829312     0.122522       0.518010    0.323278
9        0.489284     0.122141       0.252777    0.172602

### Subsetting
##### 1. Columns

In [26]:
apples = ["apple_density", "apple_mass", "apple_mass"]
df[apples]

apple_density  apple_mass  apple_mass
0       0.553962    0.049969    0.049969
1       0.721854    0.492099    0.492099
2       0.644480    0.536481    0.536481
3       0.003977    0.930725    0.930725
4       0.272998    0.873663    0.873663
5       0.725415    0.764441    0.764441
6       0.370370    0.325287    0.325287
7       0.903151    0.238228    0.238228
8       0.518010    0.323278    0.323278
9       0.252777    0.172602    0.172602

In [27]:
df[["apple_density", "apple_mass", "apple_mass"]]

apple_density  apple_mass  apple_mass
0       0.553962    0.049969    0.049969
1       0.721854    0.492099    0.492099
2       0.644480    0.536481    0.536481
3       0.003977    0.930725    0.930725
4       0.272998    0.873663    0.873663
5       0.725415    0.764441    0.764441
6       0.370370    0.325287    0.325287
7       0.903151    0.238228    0.238228
8       0.518010    0.323278    0.323278
9       0.252777    0.172602    0.172602

In [28]:
# Sorting

df.sort_values("banana_density", ascending = False)

banana_density  banana_mass  apple_density  apple_mass
6        0.973106     0.434359       0.370370    0.325287
7        0.948926     0.717877       0.903151    0.238228
2        0.940427     0.714961       0.644480    0.536481
8        0.829312     0.122522       0.518010    0.323278
1        0.727410     0.772222       0.721854    0.492099
0        0.560474     0.799471       0.553962    0.049969
9        0.489284     0.122141       0.252777    0.172602
5        0.329119     0.221963       0.725415    0.764441
3        0.302396     0.952872       0.003977    0.930725
4        0.241399     0.247323       0.272998    0.873663

In [29]:
some_new_column = np.random.random_sample((10,))
some_new_column

array([0.80926129, 0.32191251, 0.46950504, 0.45212265, 0.22271383,
       0.09046584, 0.8788993 , 0.38058344, 0.54969147, 0.22900007])

In [30]:
# Adding a column

df["mango_mass"] = some_new_column

In [31]:
pd.Series(some_new_column)

0    0.809261
1    0.321913
2    0.469505
3    0.452123
4    0.222714
5    0.090466
6    0.878899
7    0.380583
8    0.549691
9    0.229000
dtype: float64

In [32]:
df

banana_density  banana_mass  apple_density  apple_mass  mango_mass
0        0.560474     0.799471       0.553962    0.049969    0.809261
1        0.727410     0.772222       0.721854    0.492099    0.321913
2        0.940427     0.714961       0.644480    0.536481    0.469505
3        0.302396     0.952872       0.003977    0.930725    0.452123
4        0.241399     0.247323       0.272998    0.873663    0.222714
5        0.329119     0.221963       0.725415    0.764441    0.090466
6        0.973106     0.434359       0.370370    0.325287    0.878899
7        0.948926     0.717877       0.903151    0.238228    0.380583
8        0.829312     0.122522       0.518010    0.323278    0.549691
9        0.489284     0.122141       0.252777    0.172602    0.229000

In [33]:
df_new = df.sort_values("banana_density", ascending = False)

In [34]:
df_new["mango_mass"] = pd.Series(some_new_column)

In [35]:
df_new

banana_density  banana_mass  apple_density  apple_mass  mango_mass
6        0.973106     0.434359       0.370370    0.325287    0.878899
7        0.948926     0.717877       0.903151    0.238228    0.380583
2        0.940427     0.714961       0.644480    0.536481    0.469505
8        0.829312     0.122522       0.518010    0.323278    0.549691
1        0.727410     0.772222       0.721854    0.492099    0.321913
0        0.560474     0.799471       0.553962    0.049969    0.809261
9        0.489284     0.122141       0.252777    0.172602    0.229000
5        0.329119     0.221963       0.725415    0.764441    0.090466
3        0.302396     0.952872       0.003977    0.930725    0.452123
4        0.241399     0.247323       0.272998    0.873663    0.222714

In [36]:
df_new = df_new.reset_index(drop = True)

In [37]:
df_new

banana_density  banana_mass  apple_density  apple_mass  mango_mass
0        0.973106     0.434359       0.370370    0.325287    0.878899
1        0.948926     0.717877       0.903151    0.238228    0.380583
2        0.940427     0.714961       0.644480    0.536481    0.469505
3        0.829312     0.122522       0.518010    0.323278    0.549691
4        0.727410     0.772222       0.721854    0.492099    0.321913
5        0.560474     0.799471       0.553962    0.049969    0.809261
6        0.489284     0.122141       0.252777    0.172602    0.229000
7        0.329119     0.221963       0.725415    0.764441    0.090466
8        0.302396     0.952872       0.003977    0.930725    0.452123
9        0.241399     0.247323       0.272998    0.873663    0.222714

In [38]:
df_super_new = (df_new
                .sort_values("mango_mass")
                .reset_index(drop = True))

In [39]:
df_super_new

banana_density  banana_mass  apple_density  apple_mass  mango_mass
0        0.329119     0.221963       0.725415    0.764441    0.090466
1        0.241399     0.247323       0.272998    0.873663    0.222714
2        0.489284     0.122141       0.252777    0.172602    0.229000
3        0.727410     0.772222       0.721854    0.492099    0.321913
4        0.948926     0.717877       0.903151    0.238228    0.380583
5        0.302396     0.952872       0.003977    0.930725    0.452123
6        0.940427     0.714961       0.644480    0.536481    0.469505
7        0.829312     0.122522       0.518010    0.323278    0.549691
8        0.560474     0.799471       0.553962    0.049969    0.809261
9        0.973106     0.434359       0.370370    0.325287    0.878899

In [40]:
df_super_new["banana_mass"] < 0.5

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: banana_mass, dtype: bool

In [41]:
df_super_new[df_super_new["banana_mass"] < 0.5]

banana_density  banana_mass  apple_density  apple_mass  mango_mass
0        0.329119     0.221963       0.725415    0.764441    0.090466
1        0.241399     0.247323       0.272998    0.873663    0.222714
2        0.489284     0.122141       0.252777    0.172602    0.229000
7        0.829312     0.122522       0.518010    0.323278    0.549691
9        0.973106     0.434359       0.370370    0.325287    0.878899

In [42]:
df_super_new[[True, False, False, True, False, False, True, False, False, True]]

banana_density  banana_mass  apple_density  apple_mass  mango_mass
0        0.329119     0.221963       0.725415    0.764441    0.090466
3        0.727410     0.772222       0.721854    0.492099    0.321913
6        0.940427     0.714961       0.644480    0.536481    0.469505
9        0.973106     0.434359       0.370370    0.325287    0.878899

In [43]:
df_super_new[(df_super_new["mango_mass"] > .1) & (df_super_new["apple_density"] < .9)][["banana_mass", "apple_density"]]

banana_mass  apple_density
1     0.247323       0.272998
2     0.122141       0.252777
3     0.772222       0.721854
5     0.952872       0.003977
6     0.714961       0.644480
7     0.122522       0.518010
8     0.799471       0.553962
9     0.434359       0.370370